quarkus:
  rest-client:
    com.redhat.fceresol.threescale.api.clients.SourceThreescaleClient:
      url: https://3scale-all-admin.apps.lab01.gpslab.club
      scope: jakarta.inject.Singleton
      verify-host: false
    com.redhat.fceresol.threescale.api.clients.DestThreescaleClient:
      url: https://3scale-dev-admin.apps.lab01.gpslab.club
      scope: jakarta.inject.Singleton
      verify-host: false
    logging:
      scope: all
  tls:
    trust-all: true
  log:
    level: INFO
threescale:
  exportToken: bcc3458a321bc0de68ae9e9c6807a3457bd7ba2d35831741a91434d9d25ad8e7
  importToken: ee78ab54072617ec4e0ef980fced1d5a1a3b9d45ecdbdadc2465d35ad10a5402
  proxyPromoteToProduction: false
  forceDeploymentOption: self_managed
  
    


